# Generated by Django 3.1.7 on 2021-04-04 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gausscourse', '0002_course_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('curator', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='quantity_st',
        ),
        migrations.AddField(
            model_name='course',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='is_rate_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('grade', models.IntegerField(default=0)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gausscourse.coursegroup')),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gausscourse.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gausscourse.group'),
        ),
    ]
