# Generated by Django 3.1.7 on 2021-05-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gausscourse', '0003_auto_20210404_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='my_user',
        ),
        migrations.AddField(
            model_name='course',
            name='fig_created',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='fig_modified',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='fig_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='grade',
            name='created',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='modified',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(default='-', max_length=512),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default='-', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.UniqueConstraint(fields=('course', 'group'), name='one_cg_pcpg'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('user', 'course_group'), name='one_grade_pppc'),
        ),
    ]
